CREATE TABLE IF NOT EXISTS launcher_schema (id INTEGER PRIMARY KEY CHECK(id=1), version INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS testers (id TEXT PRIMARY KEY, name TEXT NOT NULL, token_hash TEXT UNIQUE NOT NULL, expires INTEGER NOT NULL, revoked INTEGER NOT NULL DEFAULT 0, created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS releases (version TEXT PRIMARY KEY, manifest TEXT NOT NULL, object_key TEXT UNIQUE NOT NULL, etag TEXT NOT NULL, created INTEGER NOT NULL, published INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS channel (id INTEGER PRIMARY KEY CHECK(id=1), version TEXT NOT NULL REFERENCES releases(version));
CREATE TABLE IF NOT EXISTS uploads (id TEXT PRIMARY KEY, version TEXT UNIQUE NOT NULL, manifest TEXT NOT NULL, object_key TEXT UNIQUE NOT NULL, multipart_id TEXT NOT NULL, offset INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'receiving', etag TEXT, verify_offset INTEGER NOT NULL DEFAULT 0, hash_state TEXT, lock_token TEXT, lock_until INTEGER NOT NULL DEFAULT 0, created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS parts (upload_id TEXT NOT NULL REFERENCES uploads(id) ON DELETE CASCADE, part_number INTEGER NOT NULL, etag TEXT NOT NULL, sha256 TEXT NOT NULL, size INTEGER NOT NULL, PRIMARY KEY(upload_id,part_number));
CREATE TABLE IF NOT EXISTS audit (id INTEGER PRIMARY KEY, time INTEGER NOT NULL, action TEXT NOT NULL, subject TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS uploads_status ON uploads(status);
INSERT INTO launcher_schema(id,version) VALUES(1,1) ON CONFLICT(id) DO NOTHING;
